apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: nvidia/cuda:10.0-base
    resources:
      limits:
        nvidia.com/gpu: 1 # requesting 1 GPU
    command: ["nvidia-smi"]
  nodeSelector:
    accelerator: nvidia
